---
inputs:
  - type: git
    branch: ${PIPELINE_REPO_BRANCH}
    service: ${PIPELINE_REPO}
    path: .deploy_rolling_satellite_pipeline
  - type: git
    branch: ${DEFINITIONS_BRANCH}
    service: ${TEKTON_CATALOG_REPO}
    path: git
  - type: git
    branch: ${DEFINITIONS_BRANCH}
    service: ${TEKTON_CATALOG_REPO}
    path: container-registry
  - type: git
    service: ${TEKTON_CATALOG_REPO}
    branch: ${DEFINITIONS_BRANCH}
    path: kubernetes-service
  - type: git
    service: ${TEKTON_CATALOG_REPO}
    branch: ${DEFINITIONS_BRANCH}
    path: toolchain
  - type: git
    branch: ${DEFINITIONS_BRANCH}
    service: ${TEKTON_CATALOG_REPO}
    path: cra
  - type: git
    service: ${TEKTON_CATALOG_REPO}
    branch: ${DEFINITIONS_BRANCH}
    path: devops-insights
  - type: git
    branch: ${DEFINITIONS_BRANCH}
    service: ${TEKTON_CATALOG_REPO}
    path: linter
  - type: git
    branch: ${DEFINITIONS_BRANCH}
    service: ${TEKTON_CATALOG_REPO}
    path: tester
  - type: git
    branch: ${DEFINITIONS_BRANCH}
    service: ${TEKTON_CATALOG_REPO}
    path: utils
triggers:
  - type: git
    name: commit-push
    eventListener: ${GIT_COMMIT_EVENT_LISTENER_NAME}
    service: ${INVENTORY_REPO}
    branch: ${DEPLOYMENT_BRANCH}
    events: { "push": true }
    properties:
      - name: pipeline-debug
        type: single_select
        value:
          "0": true
          "1": false
      - name: cluster-namespace
        value: ${CLUSTER_NAMESPACE}
        type: text
      - name: deployment-branch
        value: ${DEPLOYMENT_BRANCH}
        type: text
      - name: directory-path
        value: ${DIRECTORY_PATH}
        type: text
      - name: configuration-name
        value: ${CONFIGURATION_NAME}
        type: text
  - type: manual
    name: manual-run
    eventListener: manual-run
    properties:
      - name: pipeline-debug
        type: single_select
        value:
          "0": true
          "1": false
      - name: cluster-namespace
        value: ${CLUSTER_NAMESPACE}
        type: text
      - name: deployment-branch
        value: ${DEPLOYMENT_BRANCH}
        type: text
      - name: directory-path
        value: ${DIRECTORY_PATH}
        type: text
      - name: configuration-name
        value: ${CONFIGURATION_NAME}
        type: text

properties:
  - type: secure
    name: toolchain-apikey
    value: ${API_KEY}
  - name: apikey
    value: ${API_KEY}
  - name: git-token
    type: secure
  - name: source-repo
    value: ${INVENTORY_REPO}
    type: integration
    path: parameters.repo_url  
  - name: commons-hosted-region
    value: ${COMMONS_HOSTED_REGION}
    type: text
  - name: satellite-cluster-group
    value: ${SATELLITE_CLUSTER_GROUP}
    type: text
  - name: pipeline-name
    value: ${PIPELINE_NAME}
    type: text

  
